### PR TITLE
Fix weekly-view for new Notion databases

### LINKED ISSUE #98: weekly board view not working
Board view still shows the entire month.

### PR DESCRIPTION
**Pull request by sisi-sh**
**Which bug report or feature request do these changes address?**

Fixed #98, where weekly-view failed to target the current view in Notion's new database layout.

**What does your code do and why?**
 
This PR updates that code to extract the current view's name correctly from the new Notion databases layout at desktop and mobile sizes. It targets the container for the new view selection controls and finds the current view name within. 

On desktop (where many tabs are presented), it filters through the tabs for the current view by the border style (as there is no class or attribute to target) 
image

On mobile (where the's only a single dropdown button with the current view name, like the old database view 
image

It hides extraneous weeks by setting the height to 0 and visibility to none. 

It doens't modify any other code pertaining to the week filtering and picking methodology. 

Tested on the latest injecteed desktop app for macOS Monterey 12.2.1.

### CODE REVIEW

**Comment by forrest-herman** [comment]
This looks promising! I use the notion-enhancer/repackaged, how can I add this fix to my client? Thanks!

**Comment by sisi-sh** [comment]
> This looks promising! I use the notion-enhancer/repackaged, how can I add this fix to my client? Thanks!

unfortunately I don't think it's possible. funnily enough I tried to work with repackaged at first but it's really not meant to be modified so deeply. If you need this, I'd recommend patching Notion from the CLI (like how it was before repackaged) and pulling my changes in. though i'll comment none further, notion migraines pushed me to obsidian. thank you enhancer team, y'all nuts

File: weekly-view/client.mjs [hunk 1]
```diff
@@ -9,24 +9,49 @@
...
+      // Get view controls children nodes, convert to array, filter out non-text
+      const $viewNodes = []
+        .slice.call($view.querySelector(viewControlSelector).children)
+        .filter(node => node.tagName.toLowerCase().match(/(div|span)/g));
+
+      // Find current view by analyzing children (which changes on viewport) 
+      if ($viewNodes.length === 1)
+      {
+        // Mobile: Simple dropdown button (like legacy), text is current view
+        currentText = $viewNodes[0].innerText.toLowerCase();
```
Comment (dragonwocky) [inline weekly-view/client.mjs:33]: Is this for mobile devices, or just narrow window/screen widths?
